---
- name: "CAT I | RHEL-07-010010 | The Red Hat Enterprise Linux operating system must be configured so that the file permissions, ownership, and group membership of system files and commands match the vendor values."
  block:
    - name: Check for packages with incorrect permissions
      shell: |
        ( for i in `rpm -Va --nodeps --nosignature --nofiledigest --nosize --nomtime --nordev --nocaps --nolinkto --nouser --nogroup | egrep -i '^\.[M|U|G|.]{8}' | cut -d " " -f4,5`; do rpm -qf $i;done )
      args:
        warn: false
      register: packages_with_incorrect_permissions
      failed_when: packages_with_incorrect_permissions.rc > 1
      changed_when: false
    - name: Correct package ownership and permissions
      shell: |
        ( rpm --setugids "{{ item }}"; rpm --setperms "{{ item }}" )
      args:
        warn: false
      with_items: '{{ packages_with_incorrect_permissions.stdout_lines }}'
      when:
        - (packages_with_incorrect_permissions.stdout_lines | length > 0)
  tags:
      - CAT-I
      - RHEL-07-010010

- name: "CAT I | RHEL-07-010020 | The Red Hat Enterprise Linux operating system must be configured so that the cryptographic hash of system files and commands matches vendor values."
  block:
    - name: Check for packages with incorrect cryptographic integrity
      shell: |
        ( for i in `rpm -Va --noconfig --nolinkto --nosize --nouser --nogroup --nomtime --nomode --nodigest --nosignature | egrep -i '^..5' | cut -d " " -f4,5`; do rpm -qf $i;done )
      args:
        warn: false
      register: packages_with_incorrect_crypto
      failed_when: packages_with_incorrect_crypto.rc > 1
      changed_when: false
    - name: Correct package cryptographic integrity
      shell: |
        ( yum reinstall -y {{ item }} )
      args:
        warn: false
      register: package_fix_crypto
      failed_when: package_fix_crypto.rc > 1
      with_items: '{{ packages_with_incorrect_crypto.stdout_lines }}'
      when:
        - (packages_with_incorrect_crypto.stdout_lines | length > 0)
  tags:
      - CAT-I
      - RHEL-07-010020

- name: "CAT II | RHEL-07-010030 | The Red Hat Enterprise Linux operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon."
  block:
    - name: Check if the DoD banner is shown with a graphical logon
      shell: |
        if rpm -qa|grep -qs gnome; then
          currstatus=$(sed -n -r "/^\s*\[org\/gnome\/login-screen\]\s*$/,/^\s*\[/ s/^\s*banner-message-enable\s*=\s*(.*)$/\1/p" /etc/dconf/db/local.d/01-banner-message)
          if [[ "${currstatus}" == "true" ]]; then
            exit 0
          else
            exit 1
          fi
        else
          exit 0
        fi
      args:
        warn: false
      register: gui_banner_enable_check
      failed_when: gui_banner_enable_check.rc > 1
      changed_when: false
    - name: Enable banner on graphical logon
      shell: |
        filename="/etc/dconf/db/local.d/01-banner-message"
        section="\[org\/gnome\/login-screen\]"
        regsection="[org/gnome/login-screen]"
        varname="banner-message-enable"
        if [[ ! -f $filename ]] || sed -n "/^\s*${section}\s*$/q 1" $filename; then
            echo $regsection >> $filename
        fi
        sed -n -r "/^\s*${section}\s*$/,/^\s*\[/{/^\s*${varname}/q 10}" $filename
        if [[ $? -eq 10 ]]; then
            sed -i -r "/^\s*${section}\s*$/,/^\s*\[/ s/^(\s*${varname}\s*=\s*).*$/\1true/" $filename
        else
            sed -i "/^\s*${section}\s*$/a ${varname}=true" $filename
        fi
      args:
        warn: false
      when:
        - (gui_banner_enable_check.rc > 0)
  tags:
      - CAT-II
      - RHEL-07-010030

- name: "CAT II | RHEL-07-010040 | The Red Hat Enterprise Linux operating system must display the approved Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon."
  block:
    - name: Check for the correct DoD banner
      shell: |
        regcorrectstatus="'{{ logon_banner | regex_replace('(?s)(?<!\\n)\\n(?!(\n|$))', '') }}'"
        if rpm -qa|grep -qs gnome; then
          currstatus=$(sed -n -r "/^\s*\[org\/gnome\/login-screen\]\s*$/,/^\s*\[/ s/^\s*banner-message-text\s*=\s*(.*)$/\1/p" /etc/dconf/db/local.d/01-banner-message)
          if [[ "${currstatus}" == "${regcorrectstatus}" ]]; then
            exit 0
          else
            exit 1
          fi
        else
          exit 0
        fi
      args:
        warn: false
      register: gui_banner_correct_check
      failed_when: gui_banner_correct_check.rc > 1
      changed_when: false
    - name: Correct banner text on graphical logon
      shell: |
        filename="/etc/dconf/db/local.d/01-banner-message"
        section="\[org\/gnome\/login-screen\]"
        regsection="[org/gnome/login-screen]"
        varname="banner-message-text"
        correctstatus="'{{ logon_banner | regex_replace('(?s)(?<!\\n)\\n(?!(\n|$))', '') | regex_replace('(\(|\)|\.)', '\\\1') | regex_replace('(\\n)', '\\\\\1') }}'"
        if [[ ! -f $filename ]] || sed -n "/^\s*${section}\s*$/q 1" $filename; then
          echo "${regsection}" >> $filename
        fi
        sed -n -r "/^\s*${section}\s*$/,/^\s*\[/{/^\s*${varname}/q 10}" $filename
        if [[ $? -eq 10 ]]; then
          sed -i -r "/^\s*${section}\s*$/,/^\s*\[/ s/^(\s*${varname}\s*=\s*).*$/\1${correctstatus}/" $filename
        else
          sed -i "/^\s*${section}\s*$/a ${varname}=${correctstatus}" $filename
        fi
      args:
        warn: false
      when:
        - (gui_banner_correct_check.rc > 0)
  tags:
      - CAT-II
      - RHEL-07-010040

- name: "CAT II | RHEL-07-010050 | The Red Hat Enterprise Linux operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a command line user logon."
  block:
    - name: Check for DoD banner for console logon
      shell: |
        correctstatus=$(echo -e "{{ logon_banner }}")
        if [[ $correctstatus == $(cat /etc/issue) ]]; then
          exit 0
        else
          exit 1
        fi
      args:
        warn: false
      register: console_banner_check
      failed_when: console_banner_check.rc > 1
      changed_when: false
    - name: Correct console logon banner
      shell: |
        echo -e "{{ logon_banner }}" > /etc/issue
      args:
        warn: false
      when:
        - (console_banner_check.rc > 0)
 tags:
     - CAT-II
     - RHEL-07-010050

- name: "CAT II | RHEL-07-010060 | The Red Hat Enterprise Linux operating system must enable a user session lock until that user re-establishes access using established identification and authentication procedures."
  block:
    - name: Check for session lock
      shell: |
        if rpm -qa|grep -qs gnome; then
          currstatus=$(sed -n -r "/^\s*\[org\/gnome\/desktop\/screensaver\]\s*$/,/^\s*\[/ s/^\s*lock-enabled\s*=\s*(.*)$/\1/p" /etc/dconf/db/local.d/00-screensaver)
          if [[ "${currstatus}" == "true" ]]; then
            exit 0
          else
            exit 1
          fi
        else
          exit 0
        fi
      args:
        warn: false
      register: gui_lock_enable_check
      failed_when: gui_lock_enable_check.rc > 1
      changed_when: false
    - name: Correct session lock
      shell: |
        filename="/etc/dconf/db/local.d/00-screensaver"
        section="\[org\/gnome\/desktop\/screensaver\]"
        regsection="[org/gnome/desktop/screensaver]"
        varname="lock-enabled"
        if [[ ! -f $filename ]] || sed -n "/^\s*${section}\s*$/q 1" $filename; then
            echo $regsection >> $filename
        fi
        sed -n -r "/^\s*${section}\s*$/,/^\s*\[/{/^\s*${varname}/q 10}" $filename
        if [[ $? -eq 10 ]]; then
            sed -i -r "/^\s*${section}\s*$/,/^\s*\[/ s/^(\s*${varname}\s*=\s*).*$/\1true/" $filename
        else
            sed -i "/^\s*${section}\s*$/a ${varname}=true" $filename
        fi
        # dconf update
      args:
        warn: false
      register: testing
      when:
        - (gui_lock_enable_check.rc > 0)
 tags:
     - CAT-II
     - RHEL-07-010060

- name: "CAT II | RHEL-07-010061 | The Red Hat Enterprise Linux operating system must uniquely identify and must authenticate users using multifactor authentication via a graphical user logon."
  block:
    - name: Check for smartcard login
      shell: |
        if rpm -qa|grep -qs gnome; then
          currstatus=$(sed -n -r "/^\s*\[org\/gnome\/login-screen\]\s*$/,/^\s*\[/ s/^\s*enable-smartcard-authentication\s*=\s*(.*)$/\1/p" /etc/dconf/db/local.d/00-defaults)
          if [[ "${currstatus}" == "true" ]]; then
            exit 0
          else
            exit 1
          fi
        else
          exit 0
        fi
      args:
        warn: false
      register: smartcard_enable_check
      failed_when: smartcard_enable_check.rc > 1
      changed_when: false
    - name: Correct smartcard login
      shell: |
        filename="/etc/dconf/db/local.d/00-defaults"
        section="\[org\/gnome\/login-screen\]"
        regsection="[org/gnome/login-screen]"
        varname="enable-smartcard-authentication"
        if [[ ! -f $filename ]] || sed -n "/^\s*${section}\s*$/q 1" $filename; then
            echo $regsection >> $filename
        fi
        sed -n -r "/^\s*${section}\s*$/,/^\s*\[/{/^\s*${varname}/q 10}" $filename
        if [[ $? -eq 10 ]]; then
            sed -i -r "/^\s*${section}\s*$/,/^\s*\[/ s/^(\s*${varname}\s*=\s*).*$/\1true/" $filename
        else
            sed -i "/^\s*${section}\s*$/a ${varname}=true" $filename
        fi
        dconf update
      args:
        warn: false
      when:
        - (smartcard_enable_check.rc > 0)
 tags:
     - CAT-II
     - RHEL-07-010061

- name: "CAT II | RHEL-07-010062 | The Red Hat Enterprise Linux operating system must prevent a user from overriding the screensaver lock-enabled setting for the graphical user interface."
  block:
    - name: Check for prevention of overriding lock setting
      shell: |
        if rpm -qa|grep -qs gnome; then
          grep -qsi "/org/gnome/desktop/screensaver/lock-enabled" /etc/dconf/db/local.d/locks/*
        fi
      args:
        warn: false
      register: lock_override_check
      failed_when: lock_override_check.rc > 2
      changed_when: false
    - name: Correct lock override prevention
      shell: |
        echo "/org/gnome/desktop/screensaver/lock-enabled" >> /etc/dconf/db/local.d/locks/session
      args:
        warn: false
      when:
        - (lock_override_check.rc > 0)
  tags:
      - CAT-II
      - RHEL-07-010062

- name: "CAT II | RHEL-07-010070 | The Red Hat Enterprise Linux operating system must initiate a screensaver after a 15-minute period of inactivity for graphical user interfaces."
  block:
    - name: Check for screensaver timeout
      shell: |
        if rpm -qa|grep -qs gnome; then
          currstatus=$(sed -n -r "/^\s*\[org\/gnome\/desktop\/session\]\s*$/,/^\s*\[/ s/^\s*idle-delay\s*=\s*(.*)$/\1/p" /etc/dconf/db/local.d/00-screensaver)
          if [[ "${currstatus}" == "uint32 900" ]]; then
            exit 0
          else
            exit 1
          fi
        else
          exit 0
        fi
      args:
        warn: false
      register: screensaver_timeout_check
      failed_when: screensaver_timeout_check.rc > 1
      changed_when: false
    - name: Correct screensaver timeout
      shell: |
        filename="/etc/dconf/db/local.d/00-screensaver"
        section="\[org\/gnome\/desktop\/session\]"
        regsection="[org/gnome/desktop/session]"
        varname="idle-delay"
        status="uint32 900"
        if [[ ! -f $filename ]] || sed -n "/^\s*${section}\s*$/q 1" $filename; then
            echo $regsection >> $filename
        fi
        sed -n -r "/^\s*${section}\s*$/,/^\s*\[/{/^\s*${varname}/q 10}" $filename
        if [[ $? -eq 10 ]]; then
            sed -i -r "/^\s*${section}\s*$/,/^\s*\[/ s/^(\s*${varname}\s*=\s*).*$/\1${status}/" $filename
        else
            sed -i "/^\s*${section}\s*$/a ${varname}=${status}" $filename
        fi
        dconf update
      args:
        warn: false
      when:
        - (screensaver_timeout_check.rc > 0)
  tags:
    - CAT-II
    - RHEL-07-010070

- name: "CAT II | RHEL-07-010081 | The Red Hat Enterprise Linux operating system must prevent a user from overriding the screensaver lock-delay setting for the graphical user interface."
  block:
    - name: Check for prevention of overriding timeout setting
      shell: |
        if rpm -qa|grep -qs gnome; then
          grep -qsi "/org/gnome/desktop/screensaver/lock-delay" /etc/dconf/db/local.d/locks/*
        fi
      args:
        warn: false
      register: timeout_override_check
      failed_when: timeout_override_check.rc > 2
      changed_when: false
    - name: Correct timeout override prevention
      shell: |
        echo "/org/gnome/desktop/screensaver/lock-delay" >> /etc/dconf/db/local.d/locks/session
      args:
        warn: false
      when:
        - (timeout_override_check.rc > 0)
  tags:
      - CAT-II
      - RHEL-07-010081

- name: "CAT II | RHEL-07-010082 | The Red Hat Enterprise Linux operating system must prevent a user from overriding the session idle-delay setting for the graphical user interface."
  block:
    - name: Check for prevention of overriding idle setting
      shell: |
        if rpm -qa|grep -qs gnome; then
          grep -qsi "/org/gnome/desktop/session/idle-delay" /etc/dconf/db/local.d/locks/*
        fi
      args:
        warn: false
      register: idle_override_check
      failed_when: idle_override_check.rc > 2
      changed_when: false
    - name: Correct timeout override prevention
      shell: |
        echo "/org/gnome/desktop/session/idle-delay" >> /etc/dconf/db/local.d/locks/session
      args:
        warn: false
      when:
        - (idle_override_check.rc > 0)
  tags:
      - CAT-II
      - RHEL-07-010082
